# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pheno_website',
                'doc_host': 'https://pheno-ai.github.io',
                'git_url': 'https://github.com/pheno-ai/pheno_website',
                'lib_path': 'pheno_website'},
  'syms': {}}
